apiVersion: v1
data:
  cell-gateway-config: |
    {
        "username": "admin",
        "password": "admin",
        "apiVersion": "v0.14",
        "registerPayload": {
            "clientName": "rest_api_publisher",
            "owner": "admin",
            "grantType": "password refresh_token",
            "saasApp": true
        },
        "apimBaseUrl": "https://localhost:9443",
        "tokenEndpoint": "https://localhost:8243/token",
        "trustStore": {
            "location": "lib/platform/bre/security/ballerinaTruststore.p12",
            "password": "ballerina"
        }
    }
kind: ConfigMap
metadata:
  name: vick-config
  namespace: vick-system
